package com.website.generateEntities;
// Generated 9 Dec, 2019 1:14:57 PM by Hibernate Tools 5.4.7.Final

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private String id;
	private String orderId;
	private byte[] orderids;
	private double price;
	private byte[] product;
	private String productId;
	private int quantity;
	private byte[] orderdata;

	public OrderDetails() {
	}

	public OrderDetails(String id, double price, int quantity) {
		this.id = id;
		this.price = price;
		this.quantity = quantity;
	}

	public OrderDetails(String id, String orderId, byte[] orderids, double price, byte[] product, String productId,
			int quantity, byte[] orderdata) {
		this.id = id;
		this.orderId = orderId;
		this.orderids = orderids;
		this.price = price;
		this.product = product;
		this.productId = productId;
		this.quantity = quantity;
		this.orderdata = orderdata;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public byte[] getOrderids() {
		return this.orderids;
	}

	public void setOrderids(byte[] orderids) {
		this.orderids = orderids;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public byte[] getProduct() {
		return this.product;
	}

	public void setProduct(byte[] product) {
		this.product = product;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public byte[] getOrderdata() {
		return this.orderdata;
	}

	public void setOrderdata(byte[] orderdata) {
		this.orderdata = orderdata;
	}

}
