package com.website.generateEntities;
// Generated 9 Dec, 2019 1:14:57 PM by Hibernate Tools 5.4.7.Final

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private String productId;
	private String productCategory;
	private String productCondition;
	private String productDescription;
	private String productManufacturer;
	private String productName;
	private double productPrice;
	private String productStatus;
	private int unitInStock;

	public Product() {
	}

	public Product(String productId, double productPrice, int unitInStock) {
		this.productId = productId;
		this.productPrice = productPrice;
		this.unitInStock = unitInStock;
	}

	public Product(String productId, String productCategory, String productCondition, String productDescription,
			String productManufacturer, String productName, double productPrice, String productStatus,
			int unitInStock) {
		this.productId = productId;
		this.productCategory = productCategory;
		this.productCondition = productCondition;
		this.productDescription = productDescription;
		this.productManufacturer = productManufacturer;
		this.productName = productName;
		this.productPrice = productPrice;
		this.productStatus = productStatus;
		this.unitInStock = unitInStock;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(String productCategory) {
		this.productCategory = productCategory;
	}

	public String getProductCondition() {
		return this.productCondition;
	}

	public void setProductCondition(String productCondition) {
		this.productCondition = productCondition;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public String getProductManufacturer() {
		return this.productManufacturer;
	}

	public void setProductManufacturer(String productManufacturer) {
		this.productManufacturer = productManufacturer;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public double getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(double productPrice) {
		this.productPrice = productPrice;
	}

	public String getProductStatus() {
		return this.productStatus;
	}

	public void setProductStatus(String productStatus) {
		this.productStatus = productStatus;
	}

	public int getUnitInStock() {
		return this.unitInStock;
	}

	public void setUnitInStock(int unitInStock) {
		this.unitInStock = unitInStock;
	}

}
